import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UserProvider from "../components/context/user-context";
import { getUserFromCookies } from "../helper/helper";
import { redirect } from "next/navigation";
import ThemeProvider from "../components/context/theme-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const user = await getUserFromCookies();
  // if (!user) redirect("/")

  return (
    <html lang="en">
      <body

      >

        <ThemeProvider>
          <UserProvider user={user}>

            {children}
          </UserProvider>
        </ThemeProvider>


      </body>
    </html>
  );
}
